export const PROPERTIES_ENTITIES_ACTIONS = {
	VIEW:   'PROPERTIES_ENTITIES_VIEW',
	LIST:   'PROPERTIES_ENTITIES_LIST',
	CREATE: 'PROPERTIES_ENTITIES_CREATE',
	UPDATE: 'PROPERTIES_ENTITIES_UPDATE',
	DELETE: 'PROPERTIES_ENTITIES_DELETE',
}
