import { AUTH_ACTION } from 'modules/auth'
import { CART_ACTION } from 'modules/cart'
import { CATEGORY_ACTION } from 'modules/categories'
import { CATEGORIES_ENTITIES_ACTIONS } from 'modules/categoriesEntities'
import { CATEGORIES_RELATIONS_ACTIONS } from 'modules/categoriesRelations'
import { COMPANIES_ACTION } from 'modules/companies'
import { COMPANIES_OFFERS_ACTIONS } from 'modules/companiesOffers'
import { COMPANIES_SETTINGS_ACTIONS } from 'modules/companiesSettings'
import { CUSTOMER_ACTIONS } from 'modules/customers'
import { CUSTOMER_ADDRESSES_ACTION } from 'modules/customersAddresses'
import { COMPARES_ACTION } from 'modules/customersCompares'
import { FAVORITE_ACTION } from 'modules/customersFavorites'
import { NOTIFICATIONS_ACTIONS } from 'modules/customersNotifications'
import { CUSTOMER_SETTINGS_ACTIONS } from 'modules/customersSettings'
import { FAQ_CATEGORIES_ACTIONS } from 'modules/faqCategories'
import { FAQ_QUESTIONS_ACTIONS } from 'modules/faqQuestions'
import { ORDERS_ACTION } from 'modules/orders'
import { PAYMENT_ACTION } from 'modules/payment'
import { PRODUCTS_ATTACHMENTS_ACTIONS } from 'modules/productsAttachments'
import { PRODUCTS_BARCODES_ACTIONS } from 'modules/productsBarcodes'
import { PRODUCTS_RELATIONS_ACTIONS } from 'modules/productsRelations'
import { PROPERTIES_ACTIONS } from 'modules/properties'
import { PROPERTIES_ENTITIES_ACTIONS } from 'modules/propertiesEntities'
import { PROPERTIES_GROUPS_ACTIONS } from 'modules/propertiesGroups'
import { PROPERTIES_TYPES_ACTIONS } from 'modules/propertiesTypes'
import { TAG_ZONE_ACTIONS } from 'modules/Store/tagZone'
import { USER_ACTION } from 'modules/user'

/**
 * Intercept offline actions
 *
 * @type {Array}
 */
export const InterceptOfflineActions = [
	...[
		AUTH_ACTION.SIGN_IN,
		AUTH_ACTION.LOG_OUT,
		AUTH_ACTION.RENEW_TOKEN,
	],
	...[
		CART_ACTION.CREATE_ORDER,
		CART_ACTION.DELETE_ALL,
		CART_ACTION.DELETE,
		CART_ACTION.UPDATE,
		CART_ACTION.CREATE,
	],
	...[
		CATEGORY_ACTION.FETCH_HIERARCHICAL,
	],
	...[
		CUSTOMER_ACTIONS.DELETE,
		CUSTOMER_ACTIONS.UPDATE,
		CUSTOMER_ACTIONS.CREATE,
	],
	...[
		CUSTOMER_SETTINGS_ACTIONS.UPDATE,
	],
	...[
		ORDERS_ACTION.PAY,
	],
	...[
		PAYMENT_ACTION.SET_MAIN,
		PAYMENT_ACTION.DELETE,
		PAYMENT_ACTION.CREATE,
	],
	...[
		FAVORITE_ACTION.DELETE,
		FAVORITE_ACTION.CREATE,
		FAVORITE_ACTION.DELETE_ALL,
	],
	...[
		COMPARES_ACTION.DELETE,
		COMPARES_ACTION.CREATE,
		COMPARES_ACTION.DELETE_ALL,
	],
	...[
		COMPANIES_ACTION.CREATE,
		COMPANIES_ACTION.UPDATE,
		COMPANIES_ACTION.DELETE,
	],
	...[
		COMPANIES_SETTINGS_ACTIONS.UPDATE,
		COMPANIES_SETTINGS_ACTIONS.DELETE,
	],
	...[
		CUSTOMER_ADDRESSES_ACTION.CREATE,
		CUSTOMER_ADDRESSES_ACTION.UPDATE,
		CUSTOMER_ADDRESSES_ACTION.DELETE,
	],
	...[
		FAQ_CATEGORIES_ACTIONS.CREATE,
		FAQ_CATEGORIES_ACTIONS.UPDATE,
		FAQ_CATEGORIES_ACTIONS.DELETE,
	],
	...[
		FAQ_QUESTIONS_ACTIONS.CREATE,
		FAQ_QUESTIONS_ACTIONS.UPDATE,
		FAQ_QUESTIONS_ACTIONS.DELETE,
	],
	...[
		TAG_ZONE_ACTIONS.CREATE,
		TAG_ZONE_ACTIONS.UPDATE,
		TAG_ZONE_ACTIONS.DELETE,
	],
	...[
		PROPERTIES_ACTIONS.CREATE,
		PROPERTIES_ACTIONS.UPDATE,
		PROPERTIES_ACTIONS.DELETE,
	],
	...[
		PROPERTIES_TYPES_ACTIONS.CREATE,
		PROPERTIES_TYPES_ACTIONS.UPDATE,
		PROPERTIES_TYPES_ACTIONS.DELETE,
	],
	...[
		PROPERTIES_GROUPS_ACTIONS.CREATE,
		PROPERTIES_GROUPS_ACTIONS.UPDATE,
		PROPERTIES_GROUPS_ACTIONS.DELETE,
	],
	...[
		PROPERTIES_ENTITIES_ACTIONS.CREATE,
		PROPERTIES_ENTITIES_ACTIONS.UPDATE,
		PROPERTIES_ENTITIES_ACTIONS.DELETE,
	],
	...[
		NOTIFICATIONS_ACTIONS.UPDATE,
	],
	...[
		COMPANIES_OFFERS_ACTIONS.DELETE,
		COMPANIES_OFFERS_ACTIONS.CREATE,
		COMPANIES_OFFERS_ACTIONS.UPDATE,
	],
	...[
		PRODUCTS_ATTACHMENTS_ACTIONS.DELETE,
		PRODUCTS_ATTACHMENTS_ACTIONS.CREATE,
		PRODUCTS_ATTACHMENTS_ACTIONS.UPDATE,
	],
	...[
		PRODUCTS_RELATIONS_ACTIONS.CREATE,
		PRODUCTS_RELATIONS_ACTIONS.DELETE,
	],
	...[
		CATEGORIES_RELATIONS_ACTIONS.CREATE,
		CATEGORIES_RELATIONS_ACTIONS.DELETE,
	],
	...[
		CATEGORIES_ENTITIES_ACTIONS.CREATE,
		CATEGORIES_ENTITIES_ACTIONS.DELETE,
	],
	...[
		PRODUCTS_BARCODES_ACTIONS.DELETE,
		PRODUCTS_BARCODES_ACTIONS.CREATE,
		PRODUCTS_BARCODES_ACTIONS.UPDATE,
	],
	...Object.values(USER_ACTION),
]
