export const PROPERTIES_TYPES_ACTIONS = {
	VIEW:   'PROPERTIES_TYPES_VIEW',
	LIST:   'PROPERTIES_TYPES_LIST',
	CREATE: 'PROPERTIES_TYPES_CREATE',
	UPDATE: 'PROPERTIES_TYPES_UPDATE',
	DELETE: 'PROPERTIES_TYPES_DELETE',
}
