export const FAQ_QUESTIONS_ACTIONS = {
	LIST:   'FAQ_QUESTIONS_LIST',
	VIEW:   'FAQ_QUESTIONS_VIEW',
	CREATE: 'FAQ_QUESTIONS_CREATE',
	UPDATE: 'FAQ_QUESTIONS_UPDATE',
	DELETE: 'FAQ_QUESTIONS_DELETE',
}
