export const COMPANIES_OFFERS_ACTIONS = {
	LIST:   'COMPANIES_OFFERS_LIST',
	CREATE: 'COMPANIES_OFFERS_CREATE',
	VIEW:   'COMPANIES_OFFERS_VIEW',
	UPDATE: 'COMPANIES_OFFERS_UPDATE',
	DELETE: 'COMPANIES_OFFERS_DELETE',
}
