export const FAQ_CATEGORIES_ACTIONS = {
	LIST:   'FAQ_CATEGORIES_LIST',
	VIEW:   'FAQ_CATEGORIES_VIEW',
	CREATE: 'FAQ_CATEGORIES_CREATE',
	UPDATE: 'FAQ_CATEGORIES_UPDATE',
	DELETE: 'FAQ_CATEGORIES_DELETE',
}
